Repository RocketPy-Team/RocketPy, pull requests merged in 2022-02, with the labels that each got.

#127 Check for optional package requirement: netCDF4
  rocketpy/Environment.py
  rocketpy/Flight.py
  rocketpy/Function.py
  rocketpy/Rocket.py
  rocketpy/SolidMotor.py
  rocketpy/utilities.py
Labels: enhancement, good first issue

#122 BUG: Cld divided by zero
  docs/technical/aerodynamics/Roll_Equations.pdf
  rocketpy/Flight.py
  rocketpy/Rocket.py
  tests/test_flight.py
Labels: bug

#125 Bug: Issue 115 static margin stability
  rocketpy/Flight.py
  rocketpy/Rocket.py
  tests/test_flight.py
  tests/test_solidmotor.py
Labels: bug

#123 Enh/utc time
  docs/notebooks/environment_class_usage.ipynb
  tests/test_environment.py
Labels: enhancement

#113 Enh/class parachute
  docs/conf.py
  docs/notebooks/getting_started.ipynb
  rocketpy/Parachute.py
  rocketpy/Rocket.py
  tests/test_rocket.py
Labels: enhancement

#140 BUG: Airfoil fins normal force coefficient derivative calculation.
  rocketpy/Rocket.py
  tests/fixtures/airfoils/NACA0012-radians.txt
  tests/fixtures/airfoils/e473-10e6-degrees.csv
  tests/test_rocket.py
Labels: bug, enhancement

#149 Tests: fix test warnings
  rocketpy/Environment.py
  rocketpy/Flight.py
  tests/acceptance/test_bella_lui_rocket.py
  tests/test_flight.py
Labels: enhancement, tests
