Repository RocketPy-Team/RocketPy, pull requests merged in 2022-03, with the labels that each got.

#146 ENH: Export Flight Data
  rocketpy/Flight.py
  tests/test_flight.py
Labels: NewFeature

#151 ENH: adapt to new cftime version
  rocketpy/Environment.py
Labels: bug

#157 WIP: Front-End Integration
  rocketpy/Environment.py
Labels: NewFeature

#150 DOC: Getting Started in MATLAB
  README.md
  docs/matlab/Getting_Started.html
  docs/matlab/Getting_Started.m
  docs/matlab/Getting_Started.mlx
  docs/matlab/matlab.rst
  docs/notebooks/getting_started.ipynb
  docs/notebooks/getting_started_colab.ipynb
  docs/user/index.rst
  rocketpy/Flight.py
Labels: documentation, NewFeature

#153 Enh/dimensionality tests
  requirements_test.txt
  rocketpy/Environment.py
  rocketpy/Flight.py
  rocketpy/Function.py
  rocketpy/Rocket.py
  rocketpy/SolidMotor.py
  rocketpy/utilities.py
  tests/conftest.py
  tests/test_rocket.py
  tests/test_solidmotor.py
Labels: tests
