Repository RocketPy-Team/RocketPy, pull requests merged in 2022-09, with the labels that each got.

#221 BUG: Power on and power off drag inverted
  rocketpy/Flight.py
  rocketpy/Rocket.py
Labels: bug

#224 REL: v0.11.1
  docs/conf.py
  docs/user/installation.rst
  rocketpy/Flight.py
  rocketpy/Rocket.py
  rocketpy/__init__.py
  setup.py
Labels: release

#214 MAINT: auto assign workflows
  .github/auto-assign.yml
  .github/workflows/auto-assign-projects
  .github/workflows/auto-assign.yml
Labels: continuous_integration

#228 ENH: Add surface wind speeds, precipitation, clouds and hourly data to Environment Analysis
  rocketpy/EnvironmentAnalysis.py
Labels: enhancement

#239 Enh: Using jsonpickle to serialize EnvAnal
  requirements.txt
  rocketpy/EnvironmentAnalysis.py
Labels: Enhancement, Code architecture, Environment

#237 ENH: Refactor Env Analysis .json conversions
  docs/user/requirements.rst
  requirements.txt
  rocketpy/EnvironmentAnalysis.py
  setup.py
Labels: Enhancement, Environment

#229 ENH: automate dispersion inputs with csv
  data/dispersion csv files/Valetudo.csv
  rocketpy/utilities.py
  tests/fixtures/dispersion/Valetudo_inputs.csv
  tests/test_utilities.py
Labels: Enhancement

#230 ENH: Simple Initial Solution
  rocketpy/Flight.py
Labels: Enhancement, Exports and Prints
