Repository RocketPy-Team/RocketPy, pull requests merged in 2022-07, with the labels that each got.

#196 ENH: implement a linear varying center of mass for Hybrid motors
  data/motors/Hypertek_835CC125J-K240.eng
  docs/notebooks/HybridMotor_class_usage.ipynb
  rocketpy/Motor.py
  rocketpy/Rocket.py
  tests/test_hybridmotor.py
Labels: enhancement, NewFeature

#195 ENH: distances vs positions
  docs/notebooks/getting_started.ipynb
  docs/notebooks/getting_started_colab.ipynb
  rocketpy/Flight.py
  rocketpy/Motor.py
  rocketpy/Rocket.py
  tests/acceptance/test_bella_lui_rocket.py
  tests/acceptance/test_ndrt_2020_rocket.py
  tests/conftest.py
  tests/test_flight.py
  tests/test_rocket.py
Labels: enhancement

#202 FIX: fixing docs errors
  docs/reference/index.rst
  docs/requirements.txt
  requirements.txt
  rocketpy/__init__.py
  tests/test_environment.py
Labels: bug

#203 FIX: fixing docs error - 2nd attempt
  docs/requirements.txt
  docs/user/requirements.rst
Labels: bug
