Repository RocketPy-Team/RocketPy, pull requests merged in 2022-06, with the labels that each got.

#169 ENH: Environment Analysis - Average Temperature Along Day
  rocketpy/EnvironmentAnalysis.py
Labels: enhancement, NewFeature

#179 ENH: Environment Analysis - Units
  requirements.txt
  rocketpy/EnvironmentAnalysis.py
  rocketpy/units.py
Labels: bug

#167 ENH: Environment Analysis - Notebook
  docs/notebooks/environment_analysis_class_usage.ipynb
  docs/notebooks/environment_class_usage.ipynb
Labels: enhancement, NewFeature

#165 Enh/equilibrium altitude
  docs/notebooks/utilities_usage.ipynb
  rocketpy/Function.py
  rocketpy/utilities.py
Labels: NewFeature

#187 Delete repeated and outdated SolidMotor notebook
  docs/notebooks/SolidMotor_class_usage.ipynb
Labels: bug

#183 ENH: Environment Analysis - Example Notebook
  docs/notebooks/environment_analysis_class_usage.ipynb
  rocketpy/EnvironmentAnalysis.py
Labels: NewFeature

#189 MAINT: fix arcsec definition in docs
  rocketpy/Environment.py
Labels: documentation

#184 Maint/fixing merge from pr180
  rocketpy/Motor.py
  rocketpy/Rocket.py
Labels: enhancement, working on it

#186 ENH: new function to export to kml
  docs/notebooks/getting_started.ipynb
  docs/notebooks/getting_started_colab.ipynb
  docs/notebooks/utilities_usage.ipynb
  requirements.txt
  requirements_test.txt
  rocketpy/Flight.py
  setup.py
  tests/test_flight.py
Labels: NewFeature

#193 Enh/environment analysis right hours
  rocketpy/EnvironmentAnalysis.py
Labels: enhancement
