Repository RocketPy-Team/RocketPy, pull requests merged in 2023-05, with the labels that each got.

#336 ENH: using pydantic with the dispersion class
  docs/notebooks/dispersion_analysis/dispersion_class_usage.ipynb
  requirements.txt
  rocketpy/AeroSurfaces.py
  rocketpy/Dispersion.py
  rocketpy/Environment.py
  rocketpy/Flight.py
  rocketpy/Function.py
  rocketpy/Rocket.py
  rocketpy/__init__.py
  rocketpy/monte_carlo/DispersionModel.py
  rocketpy/monte_carlo/__init__.py
  rocketpy/monte_carlo/mc_aero_surfaces.py
  rocketpy/monte_carlo/mc_environment.py
  rocketpy/monte_carlo/mc_flight.py
  rocketpy/monte_carlo/mc_parachute.py
  rocketpy/monte_carlo/mc_rocket.py
  rocketpy/monte_carlo/mc_solid_motor.py
  rocketpy/prints/environment_prints.py
  rocketpy/prints/rocket_prints.py
  rocketpy/tools.py
  rocketpy/utilities.py
  setup.py
  tests/conftest.py
  tests/test_dispersion.py
  tests/test_environment.py
  tests/test_flight.py
  tests/test_function.py
  tests/test_rocket.py
Labels: Enhancement

#358 ENH: add " ' " to Function __repr__
  rocketpy/Function.py
  tests/test_function.py
Labels: Dispersion

#357 ENH: Environment changes for Dispersion
  docs/notebooks/topography_usage.ipynb
  rocketpy/Environment.py
  rocketpy/Flight.py
  rocketpy/prints/environment_prints.py
  tests/test_environment.py
  tests/test_flight.py
Labels: Dispersion

#356 BUG: Parachute lag warning when lag is 0 #2
  rocketpy/Flight.py
Labels: Bug, Flight

#353 Function Comparison and Identity Map
  rocketpy/Flight.py
  rocketpy/Function.py
  tests/conftest.py
  tests/test_function.py
Labels: Enhancement

#345 Enh/simpler parachute triggers
  README.md
  docs/development/rocketpy_as_developer.rst
  docs/notebooks/compare_flights_usage.ipynb
  docs/notebooks/deployable_payload_example.ipynb
  docs/notebooks/dispersion_analysis/dispersion_analysis.ipynb
  docs/notebooks/dispersion_analysis/parachute_drop_from_helicopter.ipynb
  docs/notebooks/getting_started.ipynb
  docs/notebooks/getting_started_colab.ipynb
  rocketpy/Flight.py
  rocketpy/Parachute.py
  rocketpy/Rocket.py
  tests/acceptance/test_bella_lui_rocket.py
  tests/acceptance/test_ndrt_2020_rocket.py
  tests/fixtures/acceptance/EPFL_Bella_Lui/bella_lui_flight_sim.py
  tests/fixtures/acceptance/NDRT_2020/ndrt_2020_flight_sim.py
  tests/fixtures/acceptance/PJ_Valetudo/valetudo_flight_sim.py
  tests/test_flight.py
  tests/test_rocket.py
Labels: Enhancement

#366 TST: Remove Flutter Tests
  tests/test_utilities.py
Labels: Bug, Unit tests

#369 BUG: fix standard atmosphere
  rocketpy/Environment.py
Labels: Bug, Environment
