Repository RocketPy-Team/RocketPy, pull requests merged in 2023-09, with the labels that each got.

#404 TST: env analysis tests on slow option opens matplotlib (solve #380)
  tests/test_environment_analysis.py
Labels: Bug, Unit tests

#402 BUG: env analysis altitudes ASL mistake (solve #371)
  rocketpy/EnvironmentAnalysis.py
Labels: Bug, Environment

#372 ENH: nosecone draw and bluffness
  .gitignore
  rocketpy/AeroSurface.py
  rocketpy/Rocket.py
  tests/conftest.py
  tests/test_rocket.py
Labels: Aerodynamics

#400 Add testing cases for new motor classes: LiquidMotor and HybridMotor
  rocketpy/motors/HybridMotor.py
  rocketpy/motors/LiquidMotor.py
  rocketpy/motors/Motor.py
  rocketpy/motors/SolidMotor.py
  rocketpy/prints/motor_prints.py
  tests/conftest.py
  tests/test_flight.py
  tests/test_genericmotor.py
  tests/test_hybridmotor.py
  tests/test_liquidmotor.py
  tests/test_tank.py
Labels: Unit tests, Propulsion

#406 DOC: update motor docstrings regarding coordinate systems
  rocketpy/Rocket.py
  rocketpy/motors/HybridMotor.py
  rocketpy/motors/LiquidMotor.py
  rocketpy/motors/Motor.py
  rocketpy/motors/SolidMotor.py
  rocketpy/motors/TankGeometry.py
Labels: Docs

#405 MAINT: update github workflows files
  .github/auto-assign.yml
  .github/workflows/auto-assign-projects
  .github/workflows/auto-assign.yml
  .github/workflows/test_pytest.yaml
Labels: Continuous integration

#407 BUG: absolute value of the rail button forces
  rocketpy/Flight.py
Labels: Bug

#403 FIX: env analysis dependency imports
  .github/auto-assign.yml
  .github/workflows/auto-assign-projects
  .github/workflows/auto-assign.yml
  .github/workflows/test_pytest.yaml
  docs/user/requirements.rst
  requirements-optional.txt
  requirements.txt
  rocketpy/EnvironmentAnalysis.py
  rocketpy/plots/environment_analysis_plots.py
  rocketpy/tools.py
  setup.py
  tests/test_environment_analysis.py
Labels: Bug

#409 BUG: fix parachute prints when the trigger is a lambda function
  rocketpy/Flight.py
  rocketpy/Parachute.py
  rocketpy/Rocket.py
  rocketpy/prints/parachute_prints.py
  tests/test_flight.py
Labels: Bug, Parachutes

#414 DEV: New PR Template
  .github/pull_request_template.md
Labels: Git housekeeping

#412 MAINT: deprecate some methods before v1
  rocketpy/Environment.py
  rocketpy/Flight.py
  rocketpy/Function.py
  rocketpy/Rocket.py
  tests/test_environment.py
  tests/test_function.py
Labels: Code architecture

#413 ENH: Minor Improvements and Replacement of NoseCone.draw()
  rocketpy/AeroSurface.py
  rocketpy/plots/aero_surface_plots.py
Labels: Code architecture

#420 DOC: Static images
  docs/static/institutional/projeto_jupiter_dark.png
  docs/static/institutional/projeto_jupiter_light.jpg
  docs/static/institutional/space_enterprise_at_berkeley.jpeg
  docs/static/trajectory-earth.png
Labels: Docs

#418 DOC: Refactor README
  README.md
Labels: Docs

#421 Update develop regarding README contributors
  README.md
  docs/static/institutional/projeto_jupiter_dark.png
  docs/static/institutional/projeto_jupiter_light.jpg
  docs/static/institutional/space_enterprise_at_berkeley.jpeg
  docs/static/trajectory-earth.png
Labels: Git housekeeping
