Repository RocketPy-Team/RocketPy, pull requests merged in 2023-06, with the labels that each got.

#355 ENH: AeroSurfaces(ABC) and Improvements to Rocket.aerodynamicSurfaces
  rocketpy/AeroSurface.py
  rocketpy/AeroSurfaces.py
  rocketpy/Components.py
  rocketpy/Rocket.py
  rocketpy/__init__.py
  rocketpy/prints/rocket_prints.py
  rocketpy/utilities.py
  tests/test_flight.py
  tests/test_rocket.py
Labels: Aerodynamics

#368 MAINT: convert windrose ipywidgets and jsonpickle to optional dependencies
  .github/workflows/test_pytest.yaml
  .travis.yml
  docs/user/requirements.rst
  requirements-tests.txt
  rocketpy/EnvironmentAnalysis.py
  setup.py
Labels: Code architecture

#374 MAINT: upgrade netcdf4 requirement
  docs/user/requirements.rst
  requirements.txt
  setup.py
Labels: Bug

#365 MAINT: Dropping support for python 3.7
  .github/workflows/publish-to-pypi.yml
  .github/workflows/test_pytest.yaml
  docs/user/requirements.rst
  requirements.txt
  setup.py
Labels: Bug, Continuous integration

#364 Enh/liquid-motors-linear-algebra
  docs/user/requirements.rst
  requirements.txt
  rocketpy/Flight.py
  rocketpy/plots/environment_analysis_plots.py
  rocketpy/tools.py
  tests/test_tools_matrix.py
  tests/test_tools_vector.py
Labels: Enhancement, Flight

#383 Bug/flight without rail buttons
  rocketpy/Flight.py
  rocketpy/plots/flight_plots.py
  rocketpy/prints/flight_prints.py
Labels: Bug, Flight

#381 MAINT: move aero surface plots and prints
  rocketpy/AeroSurface.py
  rocketpy/plots/__init__.py
  rocketpy/plots/aero_surface_plots.py
  rocketpy/prints/__init__.py
  rocketpy/prints/aero_surface_prints.py
  tests/test_rocket.py
Labels: Code architecture, Outputs

#376 ENH new utility functions
  rocketpy/utilities.py
  tests/test_utilities.py
Labels: Enhancement, Code architecture

#384 FIX: funcify titles - pt1
  rocketpy/Function.py
Labels: Bug

#387 ENH: Move Motor Plots and Prints
  rocketpy/motors/Fluid.py
  rocketpy/motors/HybridMotor.py
  rocketpy/motors/LiquidMotor.py
  rocketpy/motors/Motor.py
  rocketpy/motors/SolidMotor.py
  rocketpy/motors/Tank.py
  rocketpy/motors/TankGeometry.py
  rocketpy/plots/__init__.py
  rocketpy/plots/fluid_plots.py
  rocketpy/plots/hybrid_motor_plots.py
  rocketpy/plots/liquid_motor_plots.py
  rocketpy/plots/motor_plots.py
  rocketpy/plots/rocket_plots.py
  rocketpy/plots/solid_motor_plots.py
  rocketpy/plots/tank_geometry_plots.py
  rocketpy/plots/tank_plots.py
  rocketpy/prints/__init__.py
  rocketpy/prints/fluid_prints.py
  rocketpy/prints/hybrid_motor_prints.py
  rocketpy/prints/liquid_motor_prints.py
  rocketpy/prints/motor_prints.py
  rocketpy/prints/rocket_prints.py
  rocketpy/prints/solid_motor_prints.py
  rocketpy/prints/tank_geometry_prints.py
  rocketpy/prints/tank_prints.py
Labels: Code architecture, Outputs
