Repository RocketPy-Team/RocketPy, pull requests merged in 2023-11, with the labels that each got.

#408 TST: new set of tests to the Flight class
  tests/conftest.py
  tests/test_flight.py
Labels: Unit tests

#452 DOC: Add documentation on how to build the docs
  docs/development/build_docs.rst
  docs/development/index.rst
Labels: Docs

#442 MNT: making simple refactors in the Flight class
  rocketpy/simulation/flight.py
Labels: Docs, Code architecture, Flight

#459 ENH: Add mass_flow_rate() to GenericMotor class
  rocketpy/motors/motor.py
Labels: Propulsion

#456 ENH: Add _MotorPlots Inheritance to Motor Plots Classes
  rocketpy/plots/hybrid_motor_plots.py
  rocketpy/plots/liquid_motor_plots.py
  rocketpy/plots/motor_plots.py
  rocketpy/plots/solid_motor_plots.py
Labels: Propulsion, Code architecture, Outputs

#445 DOCs: improve mass and inertia docs
  rocketpy/motors/hybrid_motor.py
  rocketpy/motors/liquid_motor.py
  rocketpy/motors/motor.py
  rocketpy/motors/solid_motor.py
  rocketpy/motors/tank.py
  rocketpy/prints/rocket_prints.py
  rocketpy/rocket/rocket.py
  rocketpy/utilities.py
Labels: Docs

#458 MNT: add codecov integration
  .github/workflows/test_pytest.yaml
  README.md
Labels: Continuous integration

#448 ENH: workflows update and new docker files
  .dockerignore
  .github/workflows/test_pytest.yaml
  .travis.yml
  Dockerfile
  README.md
  docker-compose.yml
  docs/development/docker.rst
  docs/development/index.rst
Labels: Continuous integration

#461 MNT: update develop branch with changes from master
  .dockerignore
  .github/workflows/test_pytest.yaml
  .travis.yml
  Dockerfile
  README.md
  docker-compose.yml
  docs/development/build_docs.rst
  docs/development/docker.rst
  docs/development/index.rst
  rocketpy/motors/hybrid_motor.py
  rocketpy/motors/liquid_motor.py
  rocketpy/motors/motor.py
  rocketpy/motors/solid_motor.py
  rocketpy/motors/tank.py
  rocketpy/prints/rocket_prints.py
  rocketpy/rocket/rocket.py
  rocketpy/simulation/flight.py
  rocketpy/utilities.py
  tests/test_flight.py
Labels: Help wanted

#446 DOCs: linter corrections to Function class
  .flake8
  .pylintrc
  requirements-tests.txt
  rocketpy/mathutils/function.py
  rocketpy/plots/aero_surface_plots.py
  tests/test_flight.py
Labels: Docs

#451 BUG: User input checks added for Function class
  rocketpy/mathutils/function.py
  tests/test_function.py
Labels: Bug

#455 ENH: Spherical Caps Included in Total Length
  docs/examples/SEB_liquid_motor.ipynb
  rocketpy/motors/tank_geometry.py
  tests/conftest.py
  tests/test_tank.py
Labels: Bug, Propulsion

#464 DOC: add documentation for flight data export.
  docs/requirements.txt
  docs/user/first_simulation.rst
Labels: Docs

#436 ENH: draw motors
  rocketpy/motors/hybrid_motor.py
  rocketpy/motors/liquid_motor.py
  rocketpy/motors/solid_motor.py
  rocketpy/motors/tank.py
  rocketpy/plots/hybrid_motor_plots.py
  rocketpy/plots/liquid_motor_plots.py
  rocketpy/plots/motor_plots.py
  rocketpy/plots/rocket_plots.py
  rocketpy/plots/solid_motor_plots.py
  rocketpy/plots/tank_plots.py
  tests/test_flight.py
Labels: Enhancement

#465 DOC: Documentation for Function Class Usage
  docs/reference/classes/Function.rst
  docs/user/function.rst
  docs/user/index.rst
  rocketpy/mathutils/function.py
Labels: Docs

#468 DOC: Include Draw Method in Docs
  docs/user/first_simulation.rst
  docs/user/motors/hybridmotor.rst
  docs/user/motors/liquidmotor.rst
  docs/user/motors/tanks.rst
  docs/user/rocket.rst
Labels: Docs

#467 TST: new set of tests
  rocketpy/mathutils/function.py
  tests/test_flight.py
  tests/test_function.py
  tests/test_rocket.py
Labels: Unit tests

#471 BUG: Fix find_input() Function to Return a Single Value
  rocketpy/mathutils/function.py
Labels: Bug

#470 MNT: solve warnings
  .pylintrc
  rocketpy/mathutils/function.py
  rocketpy/motors/liquid_motor.py
  rocketpy/plots/rocket_plots.py
Labels: Unit tests, Outputs

#472 DOC: Add RocketPy change log file
  .github/pull_request_template.md
  CHANGELOG.md
Labels: Docs

#476 HOTFIX: Negative Static Margin
  docs/conf.py
  docs/user/installation.rst
  rocketpy/rocket/rocket.py
  setup.py
  tests/test_rocket.py
Labels: Bug

#479 HOTFIX: Tanks Overfill not Being Detected
  docs/examples/SEB_liquid_motor.ipynb
  rocketpy/mathutils/function.py
  rocketpy/motors/tank.py
  tests/test_tank.py
Labels: Bug, Propulsion

#484 ENH: Prevent out of bounds Tanks from Instantiation
  CHANGELOG.md
  rocketpy/motors/tank.py
Labels: Bug, Propulsion

#491 Doc/adding tst to docs
  docs/development/style_guide.rst
Labels: Docs

#488 ENH: Function Reverse Arithmetic Priority
  CHANGELOG.md
  rocketpy/mathutils/function.py
  tests/test_function.py
Labels: Enhancement

#489 ENH: Parachute trigger doesn't work if "Apogee" is used instead of "apogee"
  CHANGELOG.md
  rocketpy/rocket/parachute.py
  rocketpy/rocket/rocket.py
Labels: Enhancement, Parachutes

#490 MNT: Add __repr__ method to Parachute class
  CHANGELOG.md
  rocketpy/rocket/parachute.py
Labels: Parachutes
