Repository RocketPy-Team/RocketPy, pull requests merged in 2023-02, with the labels that each got.

#332 FIX: Implementation of analytical integral of linearly interpolated Functions
  rocketpy/AeroSurfaces.py
  rocketpy/EnvironmentAnalysis.py
  rocketpy/Function.py
  tests/fixtures/acceptance/EPFL_Bella_Lui/bella_lui_flight_sim.py
  tests/fixtures/acceptance/NDRT_2020/ndrt_2020_flight_sim.py
Labels: Numerical methods

#324 ENH: Parachute.info() method created
  rocketpy/Parachute.py
  rocketpy/prints/__init__.py
  rocketpy/prints/parachute_prints.py
  rocketpy/prints/rocket_prints.py
Labels: Enhancement, Parachutes

#325 MAINT: move flutter analysis into utilities submodule
  rocketpy/Flight.py
  rocketpy/utilities.py
  tests/conftest.py
  tests/test_utilities.py
Labels: Code architecture, Flight

#330 Added Piecewise class and other new Function methods
  rocketpy/Function.py
Labels: Enhancement, Numerical methods
