Repository RocketPy-Team/RocketPy, pull requests merged in 2024-09, with the labels that each got.

#636 ENH: Adds GNSS Receiver sensor
  docs/notebooks/sensors_testing.ipynb
  rocketpy/__init__.py
  rocketpy/plots/rocket_plots.py
  rocketpy/prints/sensors_prints.py
  rocketpy/rocket/parachute.py
  rocketpy/rocket/rocket.py
  rocketpy/sensors/__init__.py
  rocketpy/sensors/accelerometer.py
  rocketpy/sensors/barometer.py
  rocketpy/sensors/gnss_receiver.py
  rocketpy/sensors/gyroscope.py
  rocketpy/sensors/sensor.py
  rocketpy/simulation/flight.py
  rocketpy/tools.py
  tests/fixtures/rockets/rocket_fixtures.py
  tests/fixtures/sensors/sensors_fixtures.py
  tests/integration/test_sensor.py
  tests/unit/test_flight.py
  tests/unit/test_flight_time_nodes.py
  tests/unit/test_sensor.py
  tests/unit/test_tools.py
  tests/unit/test_tools_matrix.py
Labels: Enhancement, Controllers

#677 BUG: Zero Mass Flow Tank causing Empty Velocity Data
  CHANGELOG.md
  rocketpy/motors/liquid_motor.py
  rocketpy/motors/motor.py
Labels: Bug

#681 DOC : Halcyon Flight Example
  .vscode/settings.json
  CHANGELOG.md
  data/astg/DragCoeffOR_off.csv
  data/astg/DragCoeffOR_on.csv
  data/astg/altimeter_halcyon.csv
  data/astg/engine_Halcyon_4thHotfire.eng
  data/astg/gnss_halcyon.csv
  data/weather/euroc_2023_all_windows.nc
  docs/examples/halcyon_flight_sim.ipynb
  docs/examples/index.rst
Labels: Docs

#682 DOC : Cavour Flight Example
  CHANGELOG.md
  data/motors/cesaroni/Cesaroni_3618L995-P.eng
  data/polito/altimeter_cavour.csv
  data/polito/drag_coefficient_power_off.csv
  data/polito/drag_coefficient_power_on.csv
  docs/examples/cavour_flight_sim.ipynb
  docs/examples/index.rst
Labels: Docs

#685 BUG: Rollback Prandtl-Glauert corrections for Tail and Nose.
  CHANGELOG.md
  rocketpy/rocket/aero_surface/nose_cone.py
  rocketpy/rocket/aero_surface/tail.py
  tests/unit/test_flight.py
Labels: Bug, Aerodynamics

#687 REL: Bump versioning to RocketPy v1.4.3.
  CHANGELOG.md
  docs/conf.py
  docs/user/installation.rst
  pyproject.toml
Labels: Releases

#683 ENH: Adds Sensors classes
  .vscode/settings.json
  CHANGELOG.md
  docs/notebooks/sensors.ipynb
  docs/reference/classes/sensors/abstract/index.rst
  docs/reference/classes/sensors/abstract/inertial_sensor.rst
  docs/reference/classes/sensors/abstract/scalar_sensor.rst
  docs/reference/classes/sensors/abstract/sensor.rst
  docs/reference/classes/sensors/accelerometer.rst
  docs/reference/classes/sensors/barometer.rst
  docs/reference/classes/sensors/gnss_receiver.rst
  docs/reference/classes/sensors/gyroscope.rst
  docs/reference/classes/sensors/index.rst
  docs/user/index.rst
  rocketpy/__init__.py
  rocketpy/control/controller.py
  rocketpy/environment/tools.py
  rocketpy/mathutils/vector_matrix.py
  rocketpy/motors/tank.py
  rocketpy/plots/rocket_plots.py
  rocketpy/prints/sensors_prints.py
  rocketpy/rocket/components.py
  rocketpy/rocket/parachute.py
  rocketpy/rocket/rocket.py
  rocketpy/sensors/__init__.py
  rocketpy/sensors/accelerometer.py
  rocketpy/sensors/barometer.py
  rocketpy/sensors/gnss_receiver.py
  rocketpy/sensors/gyroscope.py
  rocketpy/sensors/sensor.py
  rocketpy/simulation/flight.py
  rocketpy/tools.py
  tests/conftest.py
  tests/fixtures/flight/flight_fixtures.py
  tests/fixtures/rockets/rocket_fixtures.py
  tests/fixtures/sensors/__init__.py
  tests/fixtures/sensors/sensors_fixtures.py
  tests/integration/test_sensor.py
  tests/unit/test_flight.py
  tests/unit/test_flight_time_nodes.py
  tests/unit/test_sensor.py
  tests/unit/test_tools.py
  tests/unit/test_tools_matrix.py
Labels: Enhancement, Controllers

#692 REL: bumps rocketpy version to v1.5.0
  .vscode/settings.json
  CHANGELOG.md
  docs/conf.py
  docs/user/installation.rst
  pyproject.toml
Labels: Releases

#691 ENH: Expand Polation Options for ND Functions.
  CHANGELOG.md
  rocketpy/mathutils/function.py
  tests/unit/test_function.py
Labels: Enhancement

#694 ENH: Free-Form Fins
  rocketpy/__init__.py
  rocketpy/plots/aero_surface_plots.py
  rocketpy/prints/aero_surface_prints.py
  rocketpy/rocket/__init__.py
  rocketpy/rocket/aero_surface/__init__.py
  rocketpy/rocket/aero_surface/fins/__init__.py
  rocketpy/rocket/aero_surface/fins/free_form_fins.py
  rocketpy/rocket/rocket.py
  tests/fixtures/surfaces/surface_fixtures.py
  tests/integration/test_rocket.py
Labels: Enhancement, Aerodynamics

#680 ENH: Generic Surfaces and Generic Linear Surfaces
  .pylintrc
  CHANGELOG.md
  README.md
  docs/reference/classes/aero_surfaces/GenericSurface.rst
  docs/reference/classes/aero_surfaces/LinearGenericSurface.rst
  docs/reference/classes/aero_surfaces/index.rst
  docs/static/institutional/faraday_team_logo.jpg
  docs/static/rocket/aeroframe.png
  docs/user/rocket/generic_surface.rst
  docs/user/rocket/rocket.rst
  rocketpy/__init__.py
  rocketpy/plots/aero_surface_plots.py
  rocketpy/plots/flight_plots.py
  rocketpy/plots/monte_carlo_plots.py
  rocketpy/plots/rocket_plots.py
  rocketpy/plots/sensitivity_plots.py
  rocketpy/prints/aero_surface_prints.py
  rocketpy/prints/rocket_prints.py
  rocketpy/prints/sensitivity_prints.py
  rocketpy/prints/sensors_prints.py
  rocketpy/rocket/__init__.py
  rocketpy/rocket/aero_surface/__init__.py
  rocketpy/rocket/aero_surface/aero_surface.py
  rocketpy/rocket/aero_surface/fins/__init__.py
  rocketpy/rocket/aero_surface/fins/fins.py
  rocketpy/rocket/aero_surface/fins/free_form_fins.py
  rocketpy/rocket/aero_surface/generic_surface.py
  rocketpy/rocket/aero_surface/linear_generic_surface.py
  rocketpy/rocket/aero_surface/nose_cone.py
  rocketpy/rocket/aero_surface/tail.py
  rocketpy/rocket/components.py
  rocketpy/rocket/rocket.py
  rocketpy/simulation/flight.py
  rocketpy/stochastic/stochastic_rocket.py
  tests/conftest.py
  tests/fixtures/generic_surfaces/__init__.py
  tests/fixtures/generic_surfaces/generic_surfaces_fixtures.py
  tests/fixtures/generic_surfaces/linear_generic_surfaces_fixtures.py
  tests/fixtures/surfaces/surface_fixtures.py
  tests/integration/test_flight.py
  tests/integration/test_rocket.py
  tests/unit/test_environment.py
  tests/unit/test_generic_surfaces.py
  tests/unit/test_linear_generic_surfaces.py
  tests/unit/test_rocket.py
Labels: Enhancement, Aerodynamics

#696 DEV: Prepare Master for v1.6
  .pylintrc
  CHANGELOG.md
  README.md
  docs/reference/classes/aero_surfaces/GenericSurface.rst
  docs/reference/classes/aero_surfaces/LinearGenericSurface.rst
  docs/reference/classes/aero_surfaces/index.rst
  docs/static/institutional/faraday_team_logo.jpg
  docs/static/rocket/aeroframe.png
  docs/user/rocket/generic_surface.rst
  docs/user/rocket/rocket.rst
  rocketpy/__init__.py
  rocketpy/mathutils/function.py
  rocketpy/plots/aero_surface_plots.py
  rocketpy/plots/flight_plots.py
  rocketpy/plots/monte_carlo_plots.py
  rocketpy/plots/rocket_plots.py
  rocketpy/plots/sensitivity_plots.py
  rocketpy/prints/aero_surface_prints.py
  rocketpy/prints/rocket_prints.py
  rocketpy/prints/sensitivity_prints.py
  rocketpy/prints/sensors_prints.py
  rocketpy/rocket/__init__.py
  rocketpy/rocket/aero_surface/__init__.py
  rocketpy/rocket/aero_surface/aero_surface.py
  rocketpy/rocket/aero_surface/fins/__init__.py
  rocketpy/rocket/aero_surface/fins/elliptical_fins.py
  rocketpy/rocket/aero_surface/fins/fins.py
  rocketpy/rocket/aero_surface/fins/free_form_fins.py
  rocketpy/rocket/aero_surface/fins/trapezoidal_fins.py
  rocketpy/rocket/aero_surface/generic_surface.py
  rocketpy/rocket/aero_surface/linear_generic_surface.py
  rocketpy/rocket/aero_surface/nose_cone.py
  rocketpy/rocket/aero_surface/tail.py
  rocketpy/rocket/components.py
  rocketpy/rocket/rocket.py
  rocketpy/simulation/flight.py
  rocketpy/stochastic/stochastic_rocket.py
  tests/conftest.py
  tests/fixtures/generic_surfaces/__init__.py
  tests/fixtures/generic_surfaces/generic_surfaces_fixtures.py
  tests/fixtures/generic_surfaces/linear_generic_surfaces_fixtures.py
  tests/fixtures/surfaces/surface_fixtures.py
  tests/integration/test_flight.py
  tests/integration/test_rocket.py
  tests/unit/test_environment.py
  tests/unit/test_function.py
  tests/unit/test_generic_surfaces.py
  tests/unit/test_linear_generic_surfaces.py
  tests/unit/test_rocket.py
Labels: Releases
