Repository RocketPy-Team/RocketPy, pull requests merged in 2024-11, with the labels that each got.

#713 ENH: add structural to total mass ratio for motor and rocket
  CHANGELOG.md
  rocketpy/motors/hybrid_motor.py
  rocketpy/motors/liquid_motor.py
  rocketpy/motors/motor.py
  rocketpy/motors/solid_motor.py
  rocketpy/prints/hybrid_motor_prints.py
  rocketpy/prints/liquid_motor_prints.py
  rocketpy/prints/motor_prints.py
  rocketpy/prints/rocket_prints.py
  rocketpy/prints/solid_motor_prints.py
  rocketpy/rocket/rocket.py
Labels: Outputs

#720 DOC: Updates README
  README.md
Labels: Docs, Git housekeeping

#724 REL: rocketpy v1.6.2
  CHANGELOG.md
  docs/conf.py
  docs/user/installation.rst
  pyproject.toml
Labels: Releases

#695 ENH: Simulation Save and Load in JSON Files
  rocketpy/_encoders.py
  rocketpy/environment/environment.py
  rocketpy/environment/environment_analysis.py
  rocketpy/mathutils/function.py
  rocketpy/mathutils/vector_matrix.py
  rocketpy/motors/fluid.py
  rocketpy/motors/hybrid_motor.py
  rocketpy/motors/liquid_motor.py
  rocketpy/motors/motor.py
  rocketpy/motors/solid_motor.py
  rocketpy/motors/tank.py
  rocketpy/motors/tank_geometry.py
  rocketpy/rocket/aero_surface/fins/elliptical_fins.py
  rocketpy/rocket/aero_surface/fins/fins.py
  rocketpy/rocket/aero_surface/fins/free_form_fins.py
  rocketpy/rocket/aero_surface/fins/trapezoidal_fins.py
  rocketpy/rocket/aero_surface/nose_cone.py
  rocketpy/rocket/aero_surface/rail_buttons.py
  rocketpy/rocket/aero_surface/tail.py
  rocketpy/rocket/components.py
  rocketpy/rocket/parachute.py
  rocketpy/rocket/rocket.py
  rocketpy/simulation/flight.py
  rocketpy/simulation/monte_carlo.py
  tests/fixtures/flight/flight_fixtures.py
  tests/fixtures/hybrid/hybrid_fixtures.py
  tests/fixtures/motor/tanks_fixtures.py
  tests/integration/test_encoding.py
  tests/integration/test_flight.py
  tests/unit/test_encoding.py
Labels: Enhancement

#737 BUG: Allow multiple sets of stochastic fins
  CHANGELOG.md
  rocketpy/stochastic/stochastic_rocket.py
Labels: Bug, Monte Carlo

#739 MNT: Place filename save parameter to the end.
  CHANGELOG.md
  rocketpy/mathutils/function.py
  rocketpy/motors/hybrid_motor.py
  rocketpy/motors/liquid_motor.py
  rocketpy/motors/motor.py
  rocketpy/motors/solid_motor.py
  rocketpy/motors/tank.py
  rocketpy/plots/aero_surface_plots.py
  rocketpy/plots/compare/compare_flights.py
  rocketpy/plots/environment_analysis_plots.py
  rocketpy/plots/environment_plots.py
  rocketpy/plots/flight_plots.py
  rocketpy/plots/hybrid_motor_plots.py
  rocketpy/plots/liquid_motor_plots.py
  rocketpy/plots/motor_plots.py
  rocketpy/plots/rocket_plots.py
  rocketpy/plots/solid_motor_plots.py
  rocketpy/plots/tank_plots.py
  rocketpy/rocket/aero_surface/fins/fins.py
  rocketpy/rocket/aero_surface/nose_cone.py
  rocketpy/rocket/rocket.py
  rocketpy/utilities.py
Labels: Refactor

#732 DOC: improvements to developers documentation
  .github/CITATION.cff
  .github/CODEOWNERS
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/clear-local-branches.ps1
  .vscode/settings.json
  docker/.dockerignore
  docker/Dockerfile
  docker/docker-compose.yml
  docs/conf.py
  docs/development/build_docs.rst
  docs/development/conflicts.rst
  docs/development/docker.rst
  docs/development/first_pr.rst
  docs/development/index.rst
  docs/development/pro_tips.rst
  docs/development/rocketpy_as_developer.rst
  docs/development/setting_up.rst
  docs/development/style_guide.rst
  docs/development/testing.rst
  docs/requirements.in
  docs/requirements.txt
  docs/user/motors/motors.rst
Labels: Docs
