Repository RocketPy-Team/RocketPy, pull requests merged in 2024-12, with the labels that each got.

#749 DEV: Updates master for v1.7.1
  .vscode/settings.json
  CHANGELOG.md
  rocketpy/environment/environment.py
  rocketpy/motors/tank.py
  rocketpy/plots/tank_geometry_plots.py
  rocketpy/plots/tank_plots.py
  rocketpy/prints/fluid_prints.py
  rocketpy/prints/tank_prints.py
  tests/conftest.py
  tests/fixtures/hybrid/__init__.py
  tests/fixtures/hybrid/hybrid_fixtures.py
  tests/fixtures/motor/data/cylindrical_oxidizer_tank_expected.csv
  tests/fixtures/motor/data/cylindrical_pressurant_tank_expected.csv
  tests/fixtures/motor/data/spherical_oxidizer_tank_expected.csv
  tests/fixtures/motor/data/tank_cad_validation_data_generator.ipynb
  tests/fixtures/motor/liquid_fixtures.py
  tests/fixtures/motor/tank_geometry_fixtures.py
  tests/fixtures/motor/tanks_fixtures.py
  tests/integration/test_tank.py
  tests/unit/test_tank.py
  tests/unit/test_tank_geometry.py
Labels: Releases

#750 REL: update version to 1.7.1 in configuration files.
  CHANGELOG.md
  docs/conf.py
  docs/user/installation.rst
  pyproject.toml
Labels: Releases

#748 ENH: Allow for Alternative and Custom ODE Solvers.
  .vscode/settings.json
  CHANGELOG.md
  rocketpy/simulation/flight.py
  tests/integration/test_flight.py
Labels: Enhancement, Flight

#757 DOCS: Erebus11 - BME Suborbitals - 2022 flight simulation
  CHANGELOG.md
  data/rockets/erebus11/drag_curve.csv
  data/rockets/erebus11/flight_data_filtered.csv
  data/rockets/erebus11/thrust_source.csv
  docs/examples/erebus_flight_sim.ipynb
  docs/examples/index.rst
Labels: Docs

#679 ENH: Expansion of Encoders Implementation for Full Flights.
  CHANGELOG.md
  docs/notebooks/monte_carlo_analysis/monte_carlo_analysis_outputs/monte_carlo_class_example.inputs.txt
  docs/notebooks/monte_carlo_analysis/monte_carlo_analysis_outputs/monte_carlo_class_example.kml
  docs/notebooks/monte_carlo_analysis/monte_carlo_analysis_outputs/monte_carlo_class_example.outputs.txt
  docs/notebooks/monte_carlo_analysis/monte_carlo_class_usage.ipynb
  requirements.txt
  rocketpy/_encoders.py
  rocketpy/environment/environment.py
  rocketpy/environment/environment_analysis.py
  rocketpy/mathutils/function.py
  rocketpy/mathutils/vector_matrix.py
  rocketpy/motors/fluid.py
  rocketpy/motors/hybrid_motor.py
  rocketpy/motors/liquid_motor.py
  rocketpy/motors/motor.py
  rocketpy/motors/solid_motor.py
  rocketpy/motors/tank.py
  rocketpy/motors/tank_geometry.py
  rocketpy/rocket/aero_surface/fins/elliptical_fins.py
  rocketpy/rocket/aero_surface/fins/fins.py
  rocketpy/rocket/aero_surface/fins/free_form_fins.py
  rocketpy/rocket/aero_surface/fins/trapezoidal_fins.py
  rocketpy/rocket/aero_surface/nose_cone.py
  rocketpy/rocket/aero_surface/rail_buttons.py
  rocketpy/rocket/aero_surface/tail.py
  rocketpy/rocket/components.py
  rocketpy/rocket/parachute.py
  rocketpy/rocket/rocket.py
  rocketpy/simulation/flight.py
  rocketpy/simulation/monte_carlo.py
  rocketpy/tools.py
  tests/fixtures/flight/flight_fixtures.py
  tests/fixtures/motor/tanks_fixtures.py
  tests/integration/test_encoding.py
  tests/integration/test_flight.py
  tests/unit/test_tank.py
Labels: Enhancement
