Repository RocketPy-Team/RocketPy, pull requests merged in 2024-06, with the labels that each got.

#607 DOC: Monte carlo documentation updates
  CHANGELOG.md
  docs/notebooks/monte_carlo_analysis/monte_carlo_analysis_outputs/monte_carlo_class_example.inputs.txt
  docs/notebooks/monte_carlo_analysis/monte_carlo_analysis_outputs/monte_carlo_class_example.kml
  docs/notebooks/monte_carlo_analysis/monte_carlo_analysis_outputs/monte_carlo_class_example.outputs.txt
  docs/notebooks/monte_carlo_analysis/monte_carlo_class_usage.ipynb
  docs/reference/classes/monte_carlo/stochastic_models/index.rst
  docs/user/index.rst
  docs/user/stochastic.rst
  rocketpy/plots/monte_carlo_plots.py
  rocketpy/simulation/monte_carlo.py
  rocketpy/stochastic/__init__.py
  rocketpy/stochastic/stochastic_aero_surfaces.py
  rocketpy/stochastic/stochastic_environment.py
  rocketpy/stochastic/stochastic_flight.py
  rocketpy/stochastic/stochastic_generic_motor.py
  rocketpy/stochastic/stochastic_model.py
  rocketpy/stochastic/stochastic_motor_model.py
  rocketpy/stochastic/stochastic_parachute.py
  rocketpy/stochastic/stochastic_rocket.py
  rocketpy/stochastic/stochastic_solid_motor.py
  tests/unit/test_stochastic_model.py
Labels: Docs, Monte Carlo

#615 MNT: Alter PYPI classifier naming.
  CHANGELOG.md
  pyproject.toml
Labels: C.I.

#616 BUG: pyproject.toml Main Module Finding.
  CHANGELOG.md
  docs/conf.py
  docs/user/installation.rst
  pyproject.toml
Labels: Bug, Releases

#584 DOC: change rocketpy landing page to standard code docs.
  CHANGELOG.md
  docs/conf.py
  docs/index.rst
  docs/requirements.in
  docs/requirements.txt
  docs/static/landing_images/api.svg
  docs/static/landing_images/contributor.svg
  docs/static/landing_images/getting_started.svg
  docs/static/landing_images/user_guide.svg
  docs/static/notebooks.css
  docs/static/rocketpy.css
Labels: Docs

#609 ENH: Add Prandtl-Glauert transformation to NoseCone and Tail
  CHANGELOG.md
  rocketpy/rocket/aero_surface.py
  tests/test_flight.py
Labels: Enhancement

#622 DEV: remove windows py3.8 from ci
  .github/workflows/test_pytest.yaml
Labels: C.I.

#624 MNT: Bump Minimum Python version to 3.9.
  .github/workflows/lint_black.yaml
  .github/workflows/publish-to-pypi.yml
  .github/workflows/test_pytest.yaml
  .pylintrc
  CHANGELOG.md
  docker-compose.yml
  docs/development/docker.rst
  docs/user/installation.rst
  pyproject.toml
Labels: C.I.

#623 MNT: Fix warnings in test suite and adds support for numpy 2.0
  CHANGELOG.md
  rocketpy/_encoders.py
  rocketpy/environment/environment.py
  rocketpy/mathutils/function.py
  rocketpy/plots/flight_plots.py
  tests/fixtures/monte_carlo/example.inputs.txt
  tests/fixtures/monte_carlo/example.outputs.txt
  tests/fixtures/monte_carlo/monte_carlo_fixtures.py
  tests/test_environment.py
  tests/test_function.py
  tests/test_monte_carlo.py
  tests/unit/test_function.py
Labels: Bug, Tests

#566 ENH: Eliminating multiple plots for inertia components
  CHANGELOG.md
  rocketpy/plots/hybrid_motor_plots.py
  rocketpy/plots/liquid_motor_plots.py
  rocketpy/plots/motor_plots.py
  rocketpy/plots/solid_motor_plots.py
Labels: Motors, Outputs
