Repository RocketPy-Team/RocketPy, pull requests merged in 2024-01, with the labels that each got.

#533 BUG: 3D trajectory plot not labeling axes
  CHANGELOG.md
  rocketpy/plots/flight_plots.py
Labels: Bug, Outputs

#521 BUG: Invalid Arguments on Two Dimensional Discretize (HOTFIX).
  CHANGELOG.md
  rocketpy/mathutils/function.py
  tests/test_function.py
Labels: Bug

#512 ENH: Remove Pydantic from Remaining Classes
  docs/notebooks/dispersion_analysis/dispersion_class_usage.ipynb
  rocketpy/monte_carlo/__init__.py
  rocketpy/monte_carlo/dispersion_model.py
  rocketpy/monte_carlo/mc_aero_surfaces.py
  rocketpy/monte_carlo/mc_environment.py
  rocketpy/monte_carlo/mc_flight.py
  rocketpy/monte_carlo/mc_generic_motor.py
  rocketpy/monte_carlo/mc_parachute.py
  rocketpy/monte_carlo/mc_rocket.py
  rocketpy/monte_carlo/mc_solid_motor.py
  rocketpy/monte_carlo/motor_dispersion_model.py
  rocketpy/rocket/parachute.py
Labels: Dispersion

#519 ENH: Argument for Optional Mutation on Function Discretize
  CHANGELOG.md
  rocketpy/mathutils/function.py
  tests/unit/test_function.py
Labels: Enhancement

#534 BUG: Parachute Pressures not being Set before All Info.
  .pylintrc
  CHANGELOG.md
  rocketpy/plots/flight_plots.py
  rocketpy/simulation/flight.py
  tests/test_flight.py
Labels: Bug

#514 ENH: adds new Function.savetxt method
  CHANGELOG.md
  docs/user/function.rst
  rocketpy/mathutils/function.py
  tests/conftest.py
  tests/unit/test_function.py
Labels: Enhancement

#535 REL: Update RocketPy version to 1.1.5
  CHANGELOG.md
  docs/conf.py
  docs/user/installation.rst
  setup.py
Labels: Releases

#538 ENH: improve Function.low_pass_filter and adds docs
  CHANGELOG.md
  docs/user/function.rst
  rocketpy/mathutils/function.py
Labels: Enhancement, Docs

#537 MNT: Encapsulate quaternion conversions
  .pylintrc
  CHANGELOG.md
  rocketpy/simulation/flight.py
  rocketpy/tools.py
Labels: Code architecture, Flight

#511 ENH Precalculate Barometric Height
  .pylintrc
  CHANGELOG.md
  rocketpy/environment/environment.py
  rocketpy/simulation/flight.py
  tests/test_environment.py
Labels: Flight

#515 ENH: Shepard Optimized Interpolation - Multiple Inputs Support
  CHANGELOG.md
  rocketpy/mathutils/function.py
  tests/test_function.py
Labels: Enhancement

#540 DOC: Installing imageio library on dispersion analysis notebook
  docs/notebooks/dispersion_analysis/dispersion_analysis.ipynb
Labels: Docs
