Repository RocketPy-Team/RocketPy, pull requests merged in 2025-03, with the labels that each got.

#775 DEV: Runs make format and updates makefile
  Makefile
  docs/examples/astra_flight_sim.ipynb
Labels: Refactor

#779 MNT: EmptyMotor class inherits from Motor(ABC)
  CHANGELOG.md
  rocketpy/motors/__init__.py
  rocketpy/motors/empty_motor.py
  rocketpy/motors/motor.py
  rocketpy/rocket/rocket.py
  rocketpy/stochastic/stochastic_rocket.py
  tests/conftest.py
  tests/fixtures/motor/empty_motor_fixtures.py
  tests/fixtures/motor/solid_motor_fixtures.py
  tests/integration/test_empty_motor.py
  tests/unit/test_rocket.py
Labels: Motors, Refactor

#778 BUG: update flight simulation logic to include burn start time
  CHANGELOG.md
  rocketpy/simulation/flight.py
Labels: Bug, Flight

#774 Bug: do not allow drawing rockets with no aerodynamic surface
  CHANGELOG.md
  rocketpy/plots/rocket_plots.py
Labels: Bug, Aerodynamics, Outputs

#792 ENH: Add Eccentricity to Stochastic Simulations
  rocketpy/rocket/rocket.py
  rocketpy/simulation/flight.py
  rocketpy/stochastic/stochastic_rocket.py
  tests/unit/test_rocket.py
Labels: Bug, Enhancement
