Repository RocketPy-Team/RocketPy, pull requests merged in 2025-04, with the labels that each got.

#798 ENH: Support for the RSE file format has been added to the library
  CHANGELOG.md
  data/motors/rse_example/rse_motor_example_file.rse
  rocketpy/motors/motor.py
  rocketpy/stochastic/stochastic_aero_surfaces.py
  tests/unit/test_genericmotor.py
Labels: Enhancement

#800 ENH: Create a rocketpy file to store flight simulations
  CHANGELOG.md
  pyproject.toml
  rocketpy/_encoders.py
  rocketpy/simulation/flight.py
  rocketpy/utilities.py
  tests/fixtures/utilities/flight_calisto_robust.rpy
  tests/integration/test_encoding.py
  tests/unit/test_utilities.py
Labels: Enhancement

#738 ENH: Implement Multivariate Rejection Sampling (MRS)
  .vscode/settings.json
  CHANGELOG.md
  docs/notebooks/monte_carlo_analysis/monte_carlo_analysis_outputs/mrs.errors.txt
  docs/notebooks/monte_carlo_analysis/monte_carlo_analysis_outputs/mrs.inputs.txt
  docs/notebooks/monte_carlo_analysis/monte_carlo_analysis_outputs/mrs.outputs.txt
  docs/reference/classes/MultivariateRejectionSampler.rst
  docs/reference/index.rst
  docs/user/index.rst
  docs/user/mrs.rst
  docs/user/sensitivity.rst
  rocketpy/__init__.py
  rocketpy/plots/monte_carlo_plots.py
  rocketpy/prints/monte_carlo_prints.py
  rocketpy/simulation/__init__.py
  rocketpy/simulation/monte_carlo.py
  rocketpy/simulation/multivariate_rejection_sampler.py
  rocketpy/tools.py
  tests/integration/test_monte_carlo.py
  tests/integration/test_multivariate_rejection_sampler.py
  tests/unit/test_multivariate_rejection_sampler.py
Labels: Enhancement, Monte Carlo

#805 Bug: Fix StochasticFlight time_overshoot None bug
  CHANGELOG.md
  rocketpy/stochastic/stochastic_flight.py
Labels: Bug, Monte Carlo

#807 BUG: LSODA solver not being detected correctly.
  CHANGELOG.md
  rocketpy/simulation/flight.py
Labels: Bug

#803 ENH: allow users to provide custom samplers
  .vscode/settings.json
  CHANGELOG.md
  docs/reference/classes/monte_carlo/stochastic_models/custom_sampler.rst
  docs/reference/classes/monte_carlo/stochastic_models/index.rst
  docs/user/custom_sampler.rst
  docs/user/index.rst
  docs/user/stochastic.rst
  rocketpy/__init__.py
  rocketpy/stochastic/__init__.py
  rocketpy/stochastic/custom_sampler.py
  rocketpy/stochastic/stochastic_model.py
  tests/conftest.py
  tests/fixtures/monte_carlo/custom_sampler_fixtures.py
  tests/fixtures/monte_carlo/stochastic_fixtures.py
  tests/unit/stochastic/test_custom_sampler.py
  tests/unit/test_stochastic_model.py
Labels: Enhancement, Monte Carlo
